version: '3.8'
services:
  face-api:
    build: .
    image: face-demo:latest
    ports:
      - "5000:5000"
    environment:
      - DATA_FOLDER=data
      - RESNET=InceptionResnetV1_vggface2.onnx
      - DEEPPIX=OULU_Protocol_2_model_0_0.onnx
      - FACEBANK=facebank.csv
      - FLASK_APP=app.app
    volumes:
      - ./data:/app/data:ro
